name: VLP
task:
data:
  train_label_path: ./data/pose_gt.train
  dev_label_path: ./data/pose_gt.dev
  test_label_path: ./data/pose_gt.test
  img_path: E:\phoenix-2014-T\PHOENIX-2014-T-release-v3\PHOENIX-2014-T\features\Phonenix-T/
  max_length: 300
training:
  wandb: disabled # online or disabled
  scale_embedding: False
  optimization:
    betas:
      - 0.9
      - 0.998
    learning_rate:
      default: 1.0e-05
      mapper: 0.001
      translation: 1.0e-05
    optimizer: Adam
    scheduler: cosineannealing
    t_max: 40
    weight_decay: 0.001
model:
  transformer:  ./pretrain_models/MBart_trimmed
  visual_encoder: ./pretrain_models/mytran
