task: S2G
device: cuda
do_translation: False
do_recognition: True
data:
  train_label_path: data/Phoenix-2014/phoenix-2014.train
  dev_label_path: data/Phoenix-2014/phoenix-2014.dev
  test_label_path: data/Phoenix-2014/phoenix-2014.test
  img_path: E:\phoenix-2014-T\PHOENIX-2014-T-release-v3\PHOENIX-2014-T\features\Phonenix-T/
  max_length: 300
  dataset_name: Phoenix-2014
  input_data: videos
  input_streams:
    - keypoint
    - level: word #word or char
      txt_lowercase: true
      max_sent_length: 400
  transform_cfg:
    img_size: 224
    color_jitter: true
    bottom_area: 0.7
    center_crop_size: 224
    center_crop: False
    randomcrop_threshold: 1
    aspect_ratio_min: 0.75
    aspect_ratio_max: 1.3
    temporal_augmentation:
      tmin: 0.5
      tmax: 1.5
gloss:
  gloss2id_file: data/Phoenix-2014/gloss2ids.pkl
  lower_case: False
testing:
  cfg:
    recognition:
      beam_size: 5
training:
  wandb: disabled # online or disabled
  overwrite: false
  random_seed: 321
  shuffle: True
  num_workers: 0
  batch_size: 2
  total_epoch: 40
  keep_last_ckpts: 5
  validation:
    unit: epoch
    freq: 1
    cfg:
      recognition:
        beam_size: 1
  optimization:
    optimizer: Adam
    learning_rate:
      default: 1.0e-3
    weight_decay: 0.001
    betas:
      - 0.9
      - 0.998
    scheduler: cosineannealing
    eta_min: 1.0e-4
    t_max: 40
model:
  RecognitionNetwork:
    input_type: keypoint
    DSTA-Net:
      net: [[64, 64, 16, 7, 2], [64, 64, 16, 3, 1],
            [64, 128, 32, 3, 1], [128, 128, 32, 3, 1],
            [128, 256, 64, 3, 2], [256, 256, 64, 3, 1],
            [256, 256, 64, 3, 1], [256, 256, 64, 3, 1],]
      body: ['face','mouth']
      left: [0,1,3,5,7,9,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111]
      right: [0,2,4,6,8,10,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132]
      face: [23,26,29,33,36,39,41,43,46,48,53,56,59,62,65,68,71,72,73,74,75,76,77,79,80,81]
    GlossTokenizer:
      gloss2id_file: data/Phoenix-2014/gloss2ids.pkl
      lower_case: False
    s3d:
      pretrained_ckpt: pretrained_models/s3ds_actioncls_ckpt #from K400
      use_block: 4
      freeze_block: 1
    fuse_method: triplehead_cat_bilateral
    rgb_visual_head:
      input_size: 832
      hidden_size: 512
      ff_size: 2048
      pe: True
      ff_kernelsize:
        - 3
        - 3
    fuse_visual_head:
      input_size: 768
      hidden_size: 512
      ff_size: 2048
      pe: True
      ff_kernelsize:
        - 3
        - 3
    left_visual_head:
      input_size: 512
      hidden_size: 512
      ff_size: 2048
      pe: True
      ff_kernelsize:
        - 3
        - 3
    right_visual_head:
      input_size: 512
      hidden_size: 512
      ff_size: 2048
      pe: True
      ff_kernelsize:
        - 3
        - 3
    cross_distillation:
      teacher_detach: True
      types:
        ensemble_last_teaches_keypoint: 1
        ensemble_last_teaches_rgb: 1
        ensemble_last_teaches_fuse: 1